name: 🏎️ Manual Umbraco Cloud Deployment (Hack)

# Manually trigger and run run
# Optionally skip the cloud-sync
on: 
  workflow_dispatch:
    inputs:
      perform_sync:
        description: 'Run Sync operation First'
        type: boolean
        default: true

jobs:
  cloud-sync:
    name: "Synchronize with Cloud"
    uses: ./.github/workflows/cloud-sync.yml
    if: ${{ inputs.perform_sync }}
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # this job is here to prevent deployment to start before the optional cloud-sync job has been done
  conditional-flow:
    name: Determining manual run flow
    runs-on: ubuntu-latest
    needs: cloud-sync
    if: ${{ success() || inputs.perform_sync == false}}
    steps:
      - run: echo "Ready to run deployment"

  # Package and Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    uses: ./.github/workflows/cloud-deployment.yml
    needs: conditional-flow
    if: always()
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}